name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'

jobs:
  run_and_test_backend_server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start Server
      run: |
        python backend/app.py &
    - name: Run Tests
      run: |
        python -m unittest discover
    - name: Run Tests
      run: |
        curl --location 'http://127.0.0.1:5000/prompt' \
        --header 'Content-Type: application/json' \
        --data '{
            "prompt": "cats"
        }'